// Pages skips dependency installation with a blank build command. Commit this
// server-only bundle; the existing Git deployment needs no build/config change.
import {build} from 'esbuild';
import {readFile, writeFile, readdir, mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {createHash} from 'node:crypto';

const root=fileURLToPath(new URL('../',import.meta.url));
const output=path.join(root,'functions/_lib/vendor');
await mkdir(output,{recursive:true});
const result=await build({absWorkingDir:root,entryPoints:['scripts/webauthn-entry.mjs'],outfile:path.join(output,'webauthn.js'),bundle:true,format:'esm',platform:'browser',target:'es2022',minify:true,legalComments:'inline',metafile:true,banner:{js:'// Generated by scripts/prepare-auth.mjs from package-lock.json. See THIRD_PARTY_NOTICES.txt. Do not edit.'}});
const packages=new Map();
for(const input of Object.keys(result.metafile.inputs)){
  if(!input.includes('node_modules/'))continue;
  let folder=path.dirname(path.resolve(root,input));
  while(folder!==root){
    try{
      const pkg=JSON.parse(await readFile(path.join(folder,'package.json'),'utf8'));
      if(pkg.name && pkg.version){packages.set(pkg.name,{folder,pkg});break;}
    }catch(error){if(error.code!=='ENOENT')throw error;}
    folder=path.dirname(folder);
  }
}
const notices=[];
for(const [name,{folder,pkg}] of [...packages].sort(([a],[b])=>a.localeCompare(b))){
  const files=(await readdir(folder)).filter(name=>/^licen[sc]e(?:\.[a-z]+)?$/i.test(name));
  if(!files.length)throw Error('Missing license for '+name);
  const license=(await Promise.all(files.map(file=>readFile(path.join(folder,file),'utf8')))).join('\n');
  notices.push(`${name} ${pkg.version}\n${pkg.homepage||pkg.repository?.url||''}\n\n${license}`);
}
await writeFile(path.join(output,'THIRD_PARTY_NOTICES.txt'),notices.join('\n\n'+'='.repeat(72)+'\n\n'));
const bytes=await readFile(path.join(output,'webauthn.js'));
console.log(`Prepared server-only WebAuthn bundle: ${bytes.length} bytes, SHA256 ${createHash('sha256').update(bytes).digest('hex')}, ${packages.size} dependency licenses.`);
