// Shared authoring for public entry pages. No browser framework or runtime dependency.
const e = value => String(value).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const route = c => `/${c.kind === 'ship' ? 'ships' : 'systems'}/${c.slug}`;
const tikTok = 'https://www.tiktok.com/@fleet_in_pieces';

function page(title, description, path, body, community = false) {
  return `<!doctype html>
<html lang="en"><head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${e(title)} — Fleet in Pieces</title><meta name="description" content="${e(description)}">
  <link rel="canonical" href="https://fleetinpieces.space${path}"><meta name="theme-color" content="#05080c">
  <meta property="og:type" content="website"><meta property="og:site_name" content="Fleet in Pieces">
  <meta property="og:title" content="${e(title)} — Fleet in Pieces"><meta property="og:description" content="${e(description)}">
  <meta property="og:url" content="https://fleetinpieces.space${path}"><meta property="og:image" content="https://fleetinpieces.space/assets/images/social-card.webp">
  <meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/icons/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/community.css"><link rel="stylesheet" href="/visitor.css">
  ${community ? '<script src="/community.js" defer></script>' : ''}<script src="/hub.js" defer></script>
</head><body class="community-page visitor-page">
<a class="skip-link" href="#main">Skip to content</a><header class="site-header wrap"></header>
<main id="main" class="wrap visitor-main">${body}</main>
<footer class="site-footer wrap"><div><a class="brand" href="/">FLEET <span>IN</span> PIECES</a><p>A space combat game. Development, in public.</p></div><div class="footer-end"><a href="/game#steam-status" data-steam>Steam page coming soon</a><a href="${tikTok}" data-social="TIKTOK_URL" target="_blank" rel="noopener noreferrer">Follow development on TikTok ↗</a><small>© 2026 Fleet in Pieces</small></div></footer>
</body></html>\n`;
}
function entries(contents) {
  return `<div class="briefing-directory">${contents.map((c,i)=>`<a class="briefing-entry" href="${route(c)}"><span class="entry-number">${String(i+1).padStart(2,'0')}</span><img src="${e(c.media.poster)}" width="${c.media.width}" height="${c.media.height}" alt="${e(c.media.title)} — development footage" loading="lazy"><div><p class="eyebrow">${c.kind === 'ship' ? 'Ship role' : 'System'} / in development</p><h2>${e(c.title)}</h2><p>${e(c.tagline)}</p><span class="entry-action">Watch. Discuss. Suggest. <span aria-hidden="true">↗</span></span></div></a>`).join('')}</div>`;
}
function topicDirectory(contents){
 return `<section class="visitor-section topic-directory" id="topics" aria-labelledby="topics-title"><div class="section-heading-row"><div><p class="eyebrow">Community / choose your discussion</p><h2 id="topics-title">What should we build next?</h2></div><a class="back-link" href="/community#propose-topic">Suggest a topic →</a></div><p class="section-note">Recently active topics first. Pick one to comment or suggest an idea. No account required.</p><div class="topic-grid" data-topic-directory>${[...contents].sort((a,b)=>a.title.localeCompare(b.title)).map(c=>`<a class="topic-tile" href="${route(c)}#suggest"><p class="eyebrow">${c.kind==='ship'?'Ship briefing':'System briefing'}</p><h3>${e(c.title)}</h3><p>${e(c.tagline)}</p><span class="topic-enter">Suggest an idea →</span></a>`).join('')}</div><p data-topic-feedback class="field-hint" role="status"></p></section>`;
}
function activityFeed(compact=false){
 return `<section class="visitor-section recent-activity" id="latest" aria-labelledby="latest-title"><div class="section-heading-row"><div><p class="eyebrow">Across the fleet / newest first</p><h2 id="latest-title">What’s new.</h2></div><a class="back-link" href="${compact?'/community#latest':'#topics'}">${compact?'All recent activity':'Browse topics'} →</a></div><p class="section-note">New topics, comments and developer replies. Dates are Pacific time.</p><div class="dispatch-grid" data-activity-list data-limit="${compact?4:0}"></div><p class="feed-feedback" data-activity-feedback role="status">Loading recent activity…</p>${compact?'':'<button class="button secondary load-more" type="button" data-activity-more hidden>Earlier activity</button>'}</section>`;
}
function topicProposal(){return `<section class="visitor-section" id="propose-topic"><div class="section-heading-row"><div><p class="eyebrow">Suggestions office / private submissions</p><h2>A discussion we’re missing?</h2></div></div><p class="section-note">Propose a topic for Fleet Command. It stays private until approved. If it gets published, your callsign will be credited prominently. Approval opens a discussion; it doesn’t promise a game feature.</p><details class="topic-proposal"><summary>Suggest a topic</summary><form id="topic-proposal-form"><label for="topic-title">Topic</label><input id="topic-title" name="title" minlength="3" maxlength="100" required placeholder="What should the fleet be talking about?"><label for="topic-body">What would you like to discuss?</label><textarea id="topic-body" name="body" minlength="8" maxlength="2000" required rows="4"></textarea><label for="topic-handle">Callsign for the credit (optional)</label><input id="topic-handle" name="handle" maxlength="32" autocomplete="nickname"><p class="field-hint" id="topic-identity">Registered members receive a profile link. Guest callsigns are unverified; blank means Anonymous crew.</p><div class="honeypot" aria-hidden="true"><input name="website" tabindex="-1" autocomplete="off" aria-label="Website"></div><button class="button primary" type="submit">Send to Fleet Command</button><p class="form-feedback" role="status" aria-live="polite"></p></form></details></section>`;}
function topicShell(){return page('__TOPIC_TITLE__','__TOPIC_DESCRIPTION__','/topics/__TOPIC_NUMBER__',`<p class="system-breadcrumb"><a href="/community#topics">All topics</a> / Community discussion</p><section class="page-intro"><p class="eyebrow">Crew-proposed / approved for discussion</p><h1>__TOPIC_TITLE__</h1><p class="topic-introduction">__TOPIC_DESCRIPTION__</p><div class="topic-credit"><span>Topic suggested by</span><strong>__TOPIC_CREDIT__</strong><small>Approved by Fleet Command · open for discussion</small></div>__TOPIC_RESPONSE__<div class="actions"><a class="button primary" href="#suggest">Add a comment ↓</a><a class="button secondary" href="#discussion">Read the discussion</a></div><p class="intro-note">__TOPIC_NOTE__</p></section><div class="participation-layout"><section id="suggest" class="contribution-block"><div class="contribution-intro"><p class="eyebrow">Add to the discussion</p><h2>Add a comment.</h2><p>No account required.</p></div><div class="contribution-form"><form id="idea-form"><label for="idea-body">Your comment</label><textarea id="idea-body" name="body" minlength="8" maxlength="2000" rows="4" required></textarea><label for="idea-handle">Callsign (optional)</label><input id="idea-handle" name="handle" maxlength="32" autocomplete="nickname" data-handle><div class="honeypot" aria-hidden="true"><input name="website" tabindex="-1" autocomplete="off" aria-label="Website"></div><button class="button primary" type="submit" disabled>Post comment</button><p class="form-feedback" role="status" aria-live="polite"></p></form><p class="field-hint">Ideas and replies are public. No private information or outside links. Guest handles are unverified.</p></div></section><section id="discussion" class="discussion-feed"><div class="feed-heading"><h2>The discussion.</h2><div class="sort-controls" role="group" aria-label="Filter ideas"><button data-sort="top" aria-pressed="false">Top</button><button data-sort="new" aria-pressed="true">Newest</button><button data-sort="responded" aria-pressed="false">Dev responded</button><button data-sort="implemented" aria-pressed="false">Implemented</button></div></div><p id="feed-feedback" class="feed-feedback" role="status">Loading the discussion…</p><div id="idea-list" class="idea-list"></div><button id="more-ideas" class="button secondary load-more" hidden>More comments</button></section></div>`,true).replaceAll('https://fleetinpieces.space/topics/__TOPIC_NUMBER__','__TOPIC_URL__').replace('class="community-page visitor-page"','class="community-page visitor-page" data-community-system="__TOPIC_SLUG__" data-content-id="__TOPIC_ID__"');}
function feed(type, title, limit = 6) {
  return `<section class="visitor-section" id="${type === 'trending' ? 'arguments' : 'implemented'}" aria-labelledby="${type}-heading"><div class="section-heading-row"><div><p class="eyebrow">${type === 'trending' ? 'Community / open to everyone' : 'Implemented from feedback'}</p><h2 id="${type}-heading">${title}</h2></div><a class="back-link" href="/community#topics">All topics ↗</a></div><p class="section-note">${type === 'trending' ? 'Back an idea, add a reply, or suggest something better. No account required.' : 'Only ideas marked implemented by Fleet Command appear here. Their authors and discussions stay attached.'}</p><p id="${type}-feedback" class="feed-feedback" role="status">Loading the ${type === 'trending' ? 'discussion' : 'record'}…</p><div id="${type}-ideas" data-limit="${limit}" class="discovery-grid"></div><noscript><p>JavaScript is needed to load discussions. <a href="/systems">Read the game briefings →</a></p></noscript></section>`;
}
function updatesList(updates, count = updates.length) {
  return `<div class="development-list">${updates.slice(0,count).map(u=>`<article id="${e(u.id)}"><div class="development-date"><time datetime="${u.date}">${new Date(u.date+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'})}</time><span>${e(u.status)}</span></div><div><h3>${e(u.title)}</h3><p>${e(u.body)}</p><a class="back-link" href="${e(u.path)}">${e(u.link)} →</a></div></article>`).join('')}</div>`;
}
function identity() {
  return `<aside class="identity-invitation"><div><p class="eyebrow">Fleet Register / optional</p><h2>Keep your callsign.</h2><p>Save your service record. Find a superior. Acquire increasingly questionable responsibilities. Posting and voting stay open to everyone.</p></div><div class="actions"><a class="button secondary" href="/register">Enter the register</a><a class="text-button" href="/fleet">Find a fleet record →</a></div></aside>`;
}
function shirt(url, merch, full = false) {
  const price = Number.isFinite(merch.price_from) ? `From US$${merch.price_from.toFixed(2)}` : 'Price on Fourthwall';
  return `<section class="procurement${full ? ' procurement-full' : ''}" id="first-issue" aria-labelledby="shirt-title"><figure class="product-mockup"><img src="${e(merch.image)}" width="${merch.image_width}" height="${merch.image_height}" loading="${full ? 'eager' : 'lazy'}" alt="Black Fleet in Pieces shirt showing the broken Kestral and Operational Status: Degraded"><figcaption>First deployment / official product mockup</figcaption></figure><div class="procurement-copy"><p class="eyebrow">Quartermaster / Merchandising Directorate</p><${full ? 'h1' : 'h2'} id="shirt-title">${full ? 'First deployment.' : 'Apparently we’re a<br>T-shirt company now.'}</${full ? 'h1' : 'h2'}><p class="shirt-name">First it was a ship. Now it’s a shirt.</p><dl class="product-identification"><div><dt>Vessel</dt><dd>${e(merch.vessel)}</dd></div><div><dt>Operational status</dt><dd>${e(merch.status)}</dd></div></dl><p>Unfortunately, Fleet Command has entered the apparel industry. The founding issue records a ship experiencing an unscheduled change of shape.</p><p class="product-price">${price} <span>Black / XS–5XL</span></p><div class="actions">${full ? `<a class="button primary" href="${e(url)}" data-quartermaster target="_blank" rel="noopener noreferrer">Buy the first issue ↗</a>` : '<a class="button secondary" href="/quartermaster">Inspect the first issue →</a>'}</div>${full ? '<p class="procurement-note">Choose your size on Fourthwall. Price varies by size; final pricing, shipping and applicable taxes are shown there. Guest checkout. No Fleet account required.</p><p class="price-date">Price checked October 3, 2026. Checkout has the current price.</p>' : ''}<p class="directorate-note">Strategic objective: shirts. Secondary objective: complete game.</p></div></section>`;
}
export function renderPages(contents, updates, productURL, merch) {
  const systems=contents.filter(c=>c.kind==='system'), ships=contents.filter(c=>c.kind==='ship');
  const home = `<section class="arrival" aria-labelledby="arrival-title"><div class="arrival-copy"><img class="arrival-wordmark" src="/assets/logo/fleet-in-pieces-transparent.webp" width="1348" height="240" alt="Fleet in Pieces" fetchpriority="high"><p class="eyebrow">PC space strategy / in active development</p><h1 id="arrival-title">Space combat.<br>Actual consequences.</h1><p class="arrival-summary">Command a finite fleet through a very large war. Real momentum. Localized damage. Ships that were probably fine a minute ago.</p><div class="actions"><a class="button primary" href="#topics">Suggest an idea ↓</a><a class="button secondary" href="/game#gameplay">See the game</a></div><p class="arrival-invitation">Help shape the game. No account required.</p><p class="arrival-note"><a href="/game#steam-status" data-steam>Steam page coming soon</a></p></div><figure class="arrival-media media-unit"><div class="media-heading"><span>Actual development footage</span><span class="recording-dot" aria-hidden="true"></span></div><video id="arrival-video" width="720" height="1280" controls muted loop playsinline preload="none" poster="/assets/images/hero-loop-poster.webp" data-loop data-auto="hero" aria-label="Ships exchanging fire and taking physical damage in Fleet in Pieces"><source src="/assets/video/hero-loop.mp4" type="video/mp4"><a href="/assets/video/hero-loop.mp4">Watch the battle</a></video><figcaption><span>Fleet combat / work in progress</span><button class="media-toggle" type="button" aria-controls="arrival-video" hidden>Play footage</button></figcaption></figure></section>
${activityFeed(true)}${topicDirectory(contents)}
${feed('trending','Your orders are suggestions.',3)}
<section class="visitor-section"><div class="section-heading-row"><div><p class="eyebrow">Development / latest dispatches</p><h2>Work in progress. In public.</h2></div><a class="back-link" href="/dev-log">Dev log ↗</a></div>${updatesList(updates,2)}</section>
${shirt(productURL,merch)}${identity()}`;
  const directory=(kind,rows)=>`<section class="page-intro"><p class="eyebrow">Fleet in Pieces / game briefings</p><h1>${kind}.</h1><p>${kind==='Ships' ? 'A carrier is a home. A rescue ship is a second chance. Meet the roles that keep a finite fleet alive.' : 'Thrust, weapons and things coming apart. Watch the actual development footage, understand the system, then help shape it.'}</p><p class="intro-note">Every briefing has an open discussion. No account required.</p></section>${entries(rows)}<nav class="directory-tail" aria-label="Keep exploring"><a href="${kind==='Ships'?'/systems':'/ships'}">${kind==='Ships'?'Explore the systems':'Meet the ships'} →</a><a href="/community">Community feedback →</a></nav>`;
  return {
    index:page('A space combat game, built in public','Fleet in Pieces is a space strategy and combat game in active development. Watch real gameplay, explore the systems and help shape the fleet.','/',home,true),
    systems:page('Systems','Explore weapons, physical damage and siege systems. Watch Fleet in Pieces development footage and join the discussion.','/systems',directory('Systems',systems)),
    ships:page('Ships','Carriers and rescue ships in Fleet in Pieces. Explore their roles, watch real development footage and contribute ideas.','/ships',directory('Ships',ships)),
    community:page('Community feedback','Suggest, vote and reply without an account. Follow Fleet Command responses and the ideas that reach the game.','/community',`<section class="page-intro"><p class="eyebrow">Community / development in public</p><h1>Help build the fleet.</h1><p>Your orders are suggestions. Pick a topic, post an idea, or back someone else’s questionable decision. No account required.</p><div class="actions"><a class="button primary" href="#latest">See what’s new ↓</a><a class="button secondary" href="#topics">Browse topics</a><a class="button secondary" href="#propose-topic">Suggest a topic</a></div></section>${activityFeed()}${topicDirectory(contents)}${topicProposal()}${feed('trending','Across the discussion board.')}${feed('implemented','From suggestion to game.')}${identity()}`,true),
    topic:topicShell(),
    'developer-replies':page('Latest developer replies','The latest Fleet Command replies across all Fleet in Pieces discussions. Read the response and join the original conversation.','/developer-replies',`<section class="page-intro"><p class="eyebrow">Fleet Command / latest responses</p><h1>Latest developer replies.</h1><p>The latest word from Fleet Command, across every topic. New and edited replies appear first.</p><a class="back-link" href="/community#topics">Browse all topics →</a></section><section class="developer-replies-feed" aria-label="Developer replies"><p id="developer-replies-feedback" class="feed-feedback" role="status">Loading developer replies…</p><div id="developer-replies-list" class="idea-list"></div><button id="developer-replies-more" class="button secondary load-more" type="button" hidden>More developer replies</button><noscript><p>JavaScript is needed to load the latest replies.</p></noscript></section>`,true),
    'dev-log':page('Development log','Short Fleet in Pieces development dispatches, current work and implemented community feedback.','/dev-log',`<section class="page-intro"><p class="eyebrow">Development / field notes</p><h1>Building the fleet.</h1><p>What is changing, what is being tested and what the crew helped put in the game. Everything shown is a work in progress.</p><a class="back-link" href="${tikTok}" data-social="TIKTOK_URL" target="_blank" rel="noopener noreferrer">Watch the development diary on TikTok ↗</a></section>${updatesList(updates)}${feed('implemented','Implemented from feedback.')}`,true),
    quartermaster:page('Quartermaster — First issue','First it was a ship. Now it is a shirt. The first Fleet in Pieces merchandise issue, with guest checkout on Fourthwall.','/quartermaster',`<p class="system-breadcrumb"><a href="/">Fleet in Pieces</a> / Quartermaster</p>${shirt(productURL,merch,true)}<aside class="quartermaster-return"><p class="eyebrow">Meanwhile, the actual strategic objective</p><h2>There is also a space combat game.</h2><p>It has carriers, missiles and a finite supply of ships. It is the reason all of this happened.</p><a class="button secondary" href="/systems">Back to the game →</a></aside>`)
  };
}
